project_id = "glzzzthgotfwoiaranmp"

[functions.check-coming-soon]
verify_jwt = false

[functions.capture-lead]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.test-integration]
verify_jwt = false

[functions.match-properties]
verify_jwt = false

[functions.send-message]
verify_jwt = false

[functions.trigger-referral-campaign]
verify_jwt = false

[functions.predict-conversion]
verify_jwt = false

[functions.batch-predictions]
verify_jwt = false

[functions.generate-investor-report]
verify_jwt = false

[functions.generate-all-investor-reports]
verify_jwt = false

[functions.paip-chat]
verify_jwt = false